on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  merge_group:
    types: [checks_requested]
permissions: read-all
name: Test
jobs:
  run-tests:
    name: Run tests
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
        - ubuntu-latest # x86
        - macos-latest # xarm
        - ubuntu-24.04-arm #arm
        - macos-15-intel # x86

    steps:
      - uses: actions/checkout@v4
      - name: Install zsh (if needed)
        if: matrix.shell == 'zsh' && startsWith(matrix.runs-on, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y zsh
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - run: ./bin/test

  run-tests-coverage:
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    if: ${{ env.CODECOV_TOKEN != '' }}
    name: Run tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests with coverage
        shell: bash
        run: ./bin/test-cov
        env:
          RUST_BACKTRACE: 1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ env.CODECOV_TOKEN }}
          slug: spinel-coop/rv
          fail_ci_if_error: true
          flags: unittests
          verbose: true
          files: lcov.info
